- name: install apache and php for Ubuntu servers
  tags: apache, apache2, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"
 
- name: install apache and php for Fedora servers
  tags: apache, fedora
  dnf:
    name:
    - httpd
    - php
    state: latest
  when: ansible_distribution == "Fedora"

- name: start httpd (Fedora)
  tags: apache, fedora, httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Fedora"

- name: start ssh (fedora)
  tags: fedora, ssh
  service:
    name: sshd
    state: started 
    enabled: yes
  when: ansible_distribution == "Fedora"

- name: change email address for admin
  tags: apache, fedora, httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Fedora"
  register: httpd 

- name: restart httpd (fedora)
  tags: apache, centos, httpd
  service: 
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
