- name: install mariadb package (Fedora)
  tags: db, mariadb, fedora
  dnf: 
    name: mariadb
    state: latest
  when: ansible_distribution == "Fedora"

- name: install mariadb package (ubuntu)
  tags: db, mariadb, ubuntu
  apt:
    name: mariadb-server  
    state: latest
  when: ansible_distribution == "Ubuntu"
